# Generated by Django 4.2.15 on 2024-08-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_academicprogress_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('annual_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('total_cost_with_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.course')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.student')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.enrollment'),
        ),
    ]
