# Generated by Django 4.2.15 on 2024-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_companyinfo_payment_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='bank_account_holder',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bank_account_iban',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_ccv',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_pdf',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_routing',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_cvc',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Bank Account', 'Bank Account'), ('Cash', 'Cash')], max_length=20),
        ),
    ]
