# Generated by Django 4.2.15 on 2024-08-30 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_rename_bank_account_holder_payment_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_routing',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_cvc',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_expiry',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_account',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
