# Generated by Django 4.2.15 on 2024-08-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_companyinfo_fiscal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='fiscal_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='CIF/NIF'),
        ),
    ]
