# Generated by Django 4.2.15 on 2024-08-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
